name: Generate Markmap and Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate Markmap for Each Markdown File
        run: |
          mkdir -p markmap-html
          for mdfile in $(find $GITHUB_WORKSPACE -name '*.md'); do
            htmlfile="./markmap-html/$(basename "${mdfile%.md}.html")"
            npx markmap-cli --no-open --offline -o "$htmlfile" "$mdfile"
          done

    #   - name: Deploy to GitHub Pages
    #     uses: JamesIves/github-pages-deploy-action@4.1.4
    #     with:
    #       branch: gh-pages # The branch the action should deploy to.
    #       folder: markmap-html # The folder the action should deploy.
    #       clean: true # Automatically remove files that are not present in the deployment folder.
